import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  // Languages
  SiJavascript, SiTypescript, SiPython, SiRust, SiGo, SiCplusplus, SiC, SiSharp, SiPhp, SiRuby, SiSwift, SiKotlin, SiDart, SiHtml5, SiSass, SiLess,
  // Frameworks & Libraries
  SiReact, SiNextdotjs, SiVuedotjs, SiNuxt, SiAngular, SiSvelte, SiTailwindcss, SiVite, SiFastapi, SiDjango, SiFlask, SiSpring, SiExpress, SiNestjs,
  SiRedux, SiGraphql, SiApollographql, SiPrisma, SiElectron, SiFlutter, SiReactos, SiAndroid,
  // Node / Runtime
  SiNodedotjs, SiDeno, SiBun,
  // Databases
  SiPostgresql, SiMongodb, SiMysql, SiSqlite, SiRedis, SiSupabase, SiFirebase, SiAppwrite,
  // Cloud & DevOps
  SiDocker, SiKubernetes, SiTerraform, SiGooglecloud, SiCloudflare, SiVercel, SiNetlify, SiDigitalocean,
  SiGit, SiGithubactions, SiGitlab, SiBitbucket, SiJenkins, SiUbuntu, SiLinux, SiMacos, SiNginx, SiApache,
  // AI
  SiGooglegemini, SiAnthropic, SiHuggingface, SiTensorflow, SiPytorch, SiScikitlearn, SiKeras, SiOpencv, SiNumpy, SiPandas, SiJupyter,
} from "react-icons/si";

import { FaWindows } from "react-icons/fa6";

// ── Corporate Logos (from thesvg) ──────────────────────
import {
  IconApple,
  IconGoogle,
  IconMicrosoft,
  IconMeta,
  IconNetflix,
  IconYoutube,
  IconTiktok,
  IconInstagram,
  IconSnapchat,
  IconX,
  IconThreads,
  IconLinkedin,
  IconDiscord,
  IconGithub,
  IconSlack,
  IconNotion,
  IconStripe,
  IconPaypal,
  IconFigma,
  IconSpotify,
  IconUber,
  IconAirbnb,
  IconTesla,
  IconZoom,
  IconAdobe,
  IconCanva,
  IconOpenai,
  IconAnthropic,
  IconVercel,
  IconNetlify,
  IconCodex,
} from "./corporateIcons";

export const iconLibrary: Record<string, IconType> = {
  // ── UI / Navigation ───────────────────────────────────────
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,

  // ── Languages ──────────────────────────────────────────────
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  rust: SiRust,
  go: SiGo,
  cpp: SiCplusplus,
  c: SiC,
  csharp: SiSharp,
  php: SiPhp,
  ruby: SiRuby,
  swift: SiSwift,
  kotlin: SiKotlin,
  dart: SiDart,
  html: SiHtml5,
  sass: SiSass,
  less: SiLess,

  // ── Frameworks & Tools ────────────────────────────────────
  react: SiReact,
  nextjs: SiNextdotjs,
  vue: SiVuedotjs,
  nuxt: SiNuxt,
  angular: SiAngular,
  svelte: SiSvelte,
  tailwindcss: SiTailwindcss,
  vite: SiVite,
  fastapi: SiFastapi,
  django: SiDjango,
  flask: SiFlask,
  spring: SiSpring,
  express: SiExpress,
  nestjs: SiNestjs,
  redux: SiRedux,
  graphql: SiGraphql,
  apollo: SiApollographql,
  prisma: SiPrisma,
  electron: SiElectron,
  flutter: SiFlutter,
  android: SiAndroid,
  reactos: SiReactos,
  nodejs: SiNodedotjs,
  deno: SiDeno,
  bun: SiBun,

  // ── Databases & Backend ──────────────────────────────────
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  sqlite: SiSqlite,
  redis: SiRedis,
  supabase: SiSupabase,
  firebase: SiFirebase,
  appwrite: SiAppwrite,

  // ── Cloud, OS & DevOps ────────────────────────────────────
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  gcp: SiGooglecloud,
  cloudflare: SiCloudflare,
  vercel: SiVercel,
  netlify: SiNetlify,
  digitalocean: SiDigitalocean,
  git: SiGit,
  githubactions: SiGithubactions,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  jenkins: SiJenkins,
  ubuntu: SiUbuntu,
  linux: SiLinux,
  macos: SiMacos,
  windows: FaWindows,
  nginx: SiNginx,
  apache: SiApache,

  // ── AI & Data Science ─────────────────────────────────────
  gemini: SiGooglegemini,
  anthropic: SiAnthropic,
  huggingface: SiHuggingface,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  scikitlearn: SiScikitlearn,
  keras: SiKeras,
  opencv: SiOpencv,
  numpy: SiNumpy,
  pandas: SiPandas,
  jupyter: SiJupyter,

  // ── Corporate / Brand (thesvg MCP) ────────────────────────
  apple: IconApple,
  google: IconGoogle,
  microsoft: IconMicrosoft,
  meta: IconMeta,
  netflix: IconNetflix,
  youtube: IconYoutube,
  tiktok: IconTiktok,
  instagram: IconInstagram,
  snapchat: IconSnapchat,
  x: IconX,
  twitter: IconX,
  threads: IconThreads,
  linkedin: IconLinkedin,
  discord: IconDiscord,
  github: IconGithub,
  slack: IconSlack,
  notion: IconNotion,
  stripe: IconStripe,
  paypal: IconPaypal,
  figma: IconFigma,
  spotify: IconSpotify,
  uber: IconUber,
  airbnb: IconAirbnb,
  tesla: IconTesla,
  zoom: IconZoom,
  adobe: IconAdobe,
  canva: IconCanva,
  openai: IconOpenai,
  anthropic_logo: IconAnthropic,
  vercel_logo: IconVercel,
  netlify_logo: IconNetlify,
  codex: IconCodex, // Using OpenAI logo for Codex as fallback since no official icon exists
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
